@startuml DCL1

class Enseignant {
    - matricule : String
    - nom : String
    - prenom : String
    - sexe : Genre
    - dateNaissance : Date
    - lieuNaissance : String
    - situationFamille : SituationFamille
    - nomConjoint : String
    - nombreEnfants : Int
    - departement : Departement
    - dateRecrutement : Date
    - estActif : Bool
}

abstract class Promotion {
    - datePromotion : Date
}

interface IndexableEnum {
    + getIndex() : Int
}

class PromotionGrade extends Promotion {
    - grade : String
}

class PromotionEchelon extends Promotion {
    - nombreEchelons : Int
}

class Diplome {
    - date : Date
    - type : TypeDiplome
}

enum TypeDiplome implements IndexableEnum {
    # Licence
    # Master
    # Doctorat
}

enum SituationFamille implements IndexableEnum {
    # Celibataire
    # Marrié
    # Divorcé
    # Veuf
}

enum Genre implements IndexableEnum {
    # Male
    # Femelle
}

enum Departement implements IndexableEnum {
    # TLSI
    # IFA
    # TroncCommunMI
}

'ASSOCIATIONS
Enseignant "1" *-- "*" Promotion
Enseignant "1" *-- "*" Diplome

PromotionGrade o-- "*" Diplome

@enduml