@startuml UseCase1
left to right direction

actor :Admin: as ad

rectangle "Gestion Personnel Enseignant" {
    (S'authentifier) as uc0

    (Gérer Enseignants) as uc1

    (Ajouter Enseignant) as uc2
    (Modifier Enseignant) as uc4
    
    (Afficher Enseignants) as uc8

    (Promouvoir) as uc5

    (par Grade) as uc6
    (par Echelon) as uc7
}

' INCLUDE
uc1 ..> uc0 : <<includes>>
uc5 ..> uc0 : <<includes>>
uc8 ..> uc0 : <<includes>>

' EXTENSIONS
uc1 <|-- uc2
uc1 <|-- uc4

uc5 <|-- uc6
uc5 <|-- uc7

' ASSOCIATIONS
ad -- uc1
ad -- uc5
ad -- uc8

@enduml