@startuml Application2

class Enseignant {
    - matricule:  String
    - nom:  String
    - prenom:  String
    - sexe:  Genre
    - dateNaissance:  Date
    - lieuNaissance:  String
    - situationFamille:  SituationFamille
    - departementAffectation:  Departement
    - laboratoireRecherche:  laboratoireRecherche
    
    
}

class PromotionRecherche {
    - datePromotion:  Date
    - gradeRecherche:  GradeDeRecherche
    
}
enum Departement{
    #TLSI
    #IFA 
    #TroncCommunINFO
}
enum laboratoireRecherche{
    #SJDF
    #DZALFA 
    #DIDI
}
class Diplome {
    - date : Date
    - type : TypeDiplome
}

enum TypeDiplome  {
    # Licence
    # Master
    # Doctorat
}

enum SituationFamille  {
    # Celibataire
    # Marrié
    # Divorcé
    # Veuf
}

enum Genre  {
    # Male
    # Female
}
Enum GradeDeRecherche {
    #AssistantEnseignement
    #MaitreDeConferences
    #ProfesseurAssistant
    #ProfesseurAssocie
    #ProfesseurTitulaire
}
Enseignant "1" o-- "0..*" PromotionRecherche 
Enseignant "1" o-- "1..*" Diplome 


@enduml