@startuml gg
left to right direction
skinparam packageStyle rectangle
actor ADMINISTRATEUR as Admin


rectangle "service de recherche "  {
    (S'authentifier) as uc0
    
     (Ajouter Enseignant)  as uc1  
     (Modifier Enseignant) as uc2
     (Afficher Enseignants) as uc4
     (Ajouter Promotion) as uc5
     (Gérer Enseignant) as uc6
      (Gérer Promotions) as uc7
     
     (Afficher Promotion)as uc8
     (Modifier Promotion)as uc9 
     
   
    
}
' INCLUDE
uc6 ....> uc0  : <<includes>>
uc7 ....> uc0 : <<includes>>

' Extends
uc6  <|-- uc1 
uc6  <|-- uc2 
uc7  <|-- uc5 
uc7  <|-- uc9 



' ASSOCIATIONS


Admin -- uc6
Admin -- uc7
Admin -- uc8
Admin -- uc4



@enduml
